### ISSUE TITLE
Bank - confirmation blocks api calls

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#17]
# Requirements
- Create a function to get a list of confirmation blocks from a bank
- Create a function to send a confirmation block to a bank
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/confirmation-blocks

**Comment by CirXe0N** [comment]
I would like to take this issue.

**Comment by VincentHch** [comment]
#35

**Comment by VincentHch** [comment]
#aaf42054f84c66586bf29d446188347ab910112cb60b775a4d6feadd5b9ae73f

**Comment by VincentHch** [comment]
If the payment is automatic, don't we need to change the assignee ?

**Comment by odetolataiwo** [comment]
@shahraizali paid
