### ISSUE TITLE
Bank - post invalid block to bank

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#18]
# Requirements
- Create a function to send an invalidated block to a bank
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/invalid-blocks

**Comment by jtavak** [comment]
Is the client library supposed to include all API functionality or just what an application would need? If it's just supposed to cover what an app would need I'm not sure if we need Validator > Bank functions.

**Comment by nishp77** [comment]
working on it, but it I need help definitely hit up on slack

**Comment by shahraizali** [comment]
let's do only 2 active issues per user. so others can get a chance as well to go through the code and actually contribute. Once the other one of yours is merged or PR is up and this is still available I'll assign it to you. what do you say?

**Comment by velibor7** [comment]
Can I take this one?

**Comment by xmac11** [comment]
Can I work on this?

**Comment by xmac11** [comment]
Account number:
8ff92d181cb09f18ef2a1b03badb5bf4a8962f7e5bb55641d0358d99bf7d5655

**Comment by odetolataiwo** [comment]
paid @shahraizali
