### ISSUE TITLE
Bank - validator confirmation services api calls

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#19]
# Requirements
- Create a function to get a list of confirmation validators
- Create a function to send a ValidatorConfirmationService object to a bank and return the response
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/validator-confirmation-services

**Comment by CirXe0N** [comment]
I would like to pick up this issue.

**Comment by odetolataiwo** [comment]
@shahraizali paid
