### ISSUE TITLE
Bank - post upgrade notice

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#20]
# Requirements
- Create a function to send a bank a message that a confirmation validator has been upgraded to a primary validator and return the response code
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/upgrade-notice

**Comment by nishp77** [comment]
working on it

**Comment by nishp77** [comment]
@velibor7 Hi I saw in the other issue you wanted to work on but someone else got it, I have another issue you could take this one?? Is it fine?

**Comment by VincentHch** [comment]
@shahraizali By the way I think we should add a `get_signature_from_message(signing_key)` method, because in some function the signature is requested but the message is generated in the function so there is no way for the user to build the signature.

**Comment by shahraizali** [comment]
Hey! @nishp77 Thank you so much for putting in the effort. really appreciate it. @VincentHch are your working on this issue now?

**Comment by shahraizali** [comment]
> get_signature_from_message(signing_key)

can you please share some references like line numbers or names of functions so that it's easier for me to track what you are talking about? Thank you

**Comment by VincentHch** [comment]
https://github.com/thenewboston-developers/thenewboston-python-client/blob/d93e75d7d2a757abfebdab82ffcaca936627e8c3/tnb/banks.py#L103

If you look at this function for example, the user must give a signature without knowing the message to sign.
I would suggest replacing : 
`"signature": signature,` by `"signature": sign(message, signing_key),`

**Comment by VincentHch** [comment]
> Hey! @nishp77 Thank you so much for putting in the effort. really appreciate it. @VincentHch are your working on this issue now?

My PR should fix this issue

**Comment by VincentHch** [comment]
Thanks for the merge. Idk if it is needed to change the assignee or sth
