### ISSUE TITLE
Bank - patch api call for validators path

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/thenewboston-python-client#22]
# Requirements
- Create a function to send patch call to bank with trust number for a validator and return the response
- include any related test(s)

# API Reference
https://thenewboston.com/bank-api/validators

**Comment by velibor7** [comment]
I'll take this one :)

**Comment by odetolataiwo** [comment]
@velibor7 account number?

@shahraizali

**Comment by odetolataiwo** [comment]
@shahraizali paid
