### ISSUE TITLE
Set max line length back to "79" to adhere to the PEP 8 code styling

### ISSUE THREAD

**Issue by CirXe0N** [thenewboston-developers/thenewboston-python-client#41]
Reasoning and conclusion can be found here:
https://github.com/thenewboston-developers/thenewboston-python-client/pull/40#discussion_r525297531

**Comment by velibor7** [comment]
This should be done after #48 is merged

**Comment by velibor7** [comment]
I'll do this one

**Comment by CirXe0N** [comment]
@velibor7  Someone (@sdhiaeddine) is already working on this. Maybe you can give him assistance if he requeres it. The PR is open for a couple of days.
PR: https://github.com/thenewboston-developers/thenewboston-python-client/pull/43

**Comment by velibor7** [comment]
Ohh I was in a rush to get issues done, I'm here if you need help. 

Also if you are you using visual studio code add vertical line helper: 

"editor.rulers": [79],
  "workbench.colorCustomizations": {
    "editorRuler.foreground": "#ff5555d8"
  },

**Comment by sdhiaeddine** [comment]
Hey @velibor7 , yes please. I still have problem fixing some "E999 SyntaxError: invalid syntax" 
Please check the commit dfe0f05 #43

**Comment by velibor7** [comment]
Do you want to do a call on discord or skype so that we don't clutter this issue?

**Comment by velibor7** [comment]
@sdhiaeddine Can you send me a message on slack so that we don't clutter this issue? I tried, but I can't find you there, just search me by my name :)

**Comment by velibor7** [comment]
514983fc77ebf39bedb82de179d2312497757e1a0e4276835844479dbfa80e5f
