### ISSUE TITLE
Return fetch_confirmation_blocks results paginated

### ISSUE THREAD

**Issue by shahraizali** [thenewboston-developers/thenewboston-python-client#45]
Currently, we are returning all the results collectively by looping over the pages we would want to avoid that. 
let's keep the "fetch_multiple_page" method might come in handy later.

https://thenewboston.com/bank-api/confirmation-blocks

Update test cases accordingly if required.

**Comment by shahraizali** [comment]
@VincentHch

**Comment by velibor7** [comment]
Is this assigned to @VincentHch or can I take it?

**Comment by shahraizali** [comment]
It's not assigned to anyone. It's part of his previous PR so I figured why not tag him. If you want you can have it. It's a minor issue.

**Comment by velibor7** [comment]
I'll take it

**Comment by VincentHch** [comment]
You can take it, are you sure that you know what you have to do @velibor7 ?
More information here : #35

**Comment by velibor7** [comment]
The more I dig into it, the less I'm sure what needs to be done. If there is someone more experienced, it's better that they take it since I'm gonna need some time to understand the api completely

**Comment by VincentHch** [comment]
Ok don't worry I'll take it. It was related to a previous PR. If you want to have a quick overview of the API you can for example go here: http://143.110.137.54 (a Bank address)

**Comment by velibor7** [comment]
Okay perfect, you take it and I'll dig into api so that I'm ready for new issues :)

**Comment by VincentHch** [comment]
@velibor7 you can try to do the 2500 issue, it is a pretty easy one, you basically have to replace the `result` value in almost every tests by a more realistic value (one returned by a real Bank/Validator)

**Comment by velibor7** [comment]
Thanks man, I'll work on that

**Comment by VincentHch** [comment]
Great 👍 Read the last comments from the mentionned PR in the issue to have a clear understanding of what to do (not every comments are related to the issue)

**Comment by velibor7** [comment]
Okay, so now I understand everything and I could easily do the 2500 task, but I'm wondering is there a more dynamic way to test this? To be more specific is comparing 2 blocks of 2 pages enough?

**Comment by shahraizali** [comment]
let's continue the conversation on that issue.

**Comment by velibor7** [comment]
This issue is covered with #48 but @VincentHch deserves the coins since I just copied his code and made it consistent with the rest :) Also thank you Vincent for help :)

**Comment by VincentHch** [comment]
A pleasure ✌️

**Comment by shahraizali** [comment]
Okay I'll make your's 3000 and close this one once you are paid I'll remind you to send 500 to @VincentHch it will be easier to track since we cannot pay unmerged PRs

**Comment by tawanike** [comment]
Paid
