### ISSUE TITLE
Bank - Fetch Test case Fixes 

### ISSUE THREAD

**Issue by shahraizali** [thenewboston-developers/thenewboston-python-client#46]
Update test cases for the following methods

**Bank test cases**
1. fetch_accounts (pagination structure missing)
2. fetch_bank_transactions (pagination structure missing)
3. fetch_validators (pagination structure missing, default_transaction_fee data type is incorrect) 
4. fetch_validator_confirmation_services  (pagination structure missing)
5. create_validator_confirmation_service (update comment it says fetch instead of create)
6. fetch_banks (test case missing)

**Validator test cases**

1. fetch_accounts (pagination structure missing)
1. fetch_confirmation_block (response need to be updated) 

We have found that the documentation we were following is a bit outdated main change required to fix all these test cases is to add pagination. kindly run the respective API call and see the structure there to follow for mock data.

All of these are Fetch requests so can easily be tested.

**Comment by shahraizali** [comment]
@velibor7 For now what we want to achieve here is just validate that all the keys are there and their structure is alright.

**Comment by velibor7** [comment]
Okay, I think 1 correctly structured page is okay then. I'll work on this

**Comment by shahraizali** [comment]
@velibor7 
This is a bank IP
143.110.137.54
This is a validator IP
54.183.17.224

You can send the calls here and see the response and we would want the test cases to have the same structure

**Comment by velibor7** [comment]
I did it for fetch accounts with #48 Tell me if I should do the same with the rest :)

**Comment by shahraizali** [comment]
yeah all of these are fetch requests you can fetch the data

**Comment by velibor7** [comment]
acc: 514983fc77ebf39bedb82de179d2312497757e1a0e4276835844479dbfa80e5f

**Comment by tawanike** [comment]
Paid
