### ISSUE TITLE
Generate documentation for the codebase using sphinx

### ISSUE THREAD

**Issue by sbalasa** [thenewboston-developers/thenewboston-python-client#49]
Once the codebase grows to a greater size keeping tracks of things will be difficult, so generating documentation will be handy.

**Comment by AbhayAysola** [comment]
I've never worked with Sphinx before, but can I work on this issue?

**Comment by sbalasa** [comment]
Sure @AbhayAysola follow https://www.sphinx-doc.org/en/1.8/usage/quickstart.html

**Comment by tawanike** [comment]
Paid
