### ISSUE TITLE
Add Pagination to the Fetch endpoints

### ISSUE THREAD

**Issue by shahraizali** [thenewboston-developers/thenewboston-python-client#55]
Currently, the methods are returning the response from the API as it is which includes the pagination information like next and prev. Now say if the user does something like
```fetch_bank_transactions()```
He will get the first page in the response of course with pagination info so he can get next records manually using that page info but we want to implement `page` as an argument to the methods like:
```fetch_bank_transactions(page=2)```
Also, we can look into adding more options like `limit` and `offset` if required.

The API response looks like this
```
{
    "count": 82,
    "next": "http://143.110.137.54/accounts?limit=50&offset=50",
    "previous": null,
    "results": [
        {
            "id": "5a8c7990-393a-4299-ae92-2f096a2c7f43",
            "created_date": "2020-10-08T02:18:07.346849Z",
            "modified_date": "2020-10-08T02:18:07.346914Z",
            "account_number": "a37e2836805975f334108b55523634c995bd2a4db610062f404510617e83126f",
            "trust": "0.00"
        },
        {
            "id": "2682963f-06b1-47d7-a2e1-1f8ec6ae98dc",
            "created_date": "2020-10-08T02:39:44.071810Z",
            "modified_date": "2020-10-08T02:39:44.071853Z",
            "account_number": "cc8fb4ebbd2b9a98a767e801ac2b0d296ced88b5d3b7d6d6e12e1d2d7635d724",
            "trust": "0.00"
        }
    ]
}
```

here next is implemented like this i.e. page=2
`"next": "http://143.110.137.54/accounts?limit=50&offset=50"`
so we have limit and offset that's how we go to the second page likewise for the third page it will be
`"next": "http://143.110.137.54/accounts?limit=50&offset=100"`

We want this implemented to all of the Fetch methods and update the test cases as well.

**Comment by CirXe0N** [comment]
I will take this.

**Comment by AmanJain27** [comment]
so to summarize, just need to change the offset number as per the page number supplied in all the fetch methods?

**Comment by shahraizali** [comment]
Yup pretty much provided if there is no limit argument.

**Comment by AmanJain27** [comment]
currently done with the fetch_accounts method. Working on other ones now. Also, updating test cases as well :D

**Comment by CirXe0N** [comment]
@AmanJain27 This issue has already been assigned.

**Comment by AmanJain27** [comment]
@CirXe0N oh okay. Sorry

**Comment by AmanJain27** [comment]
is there any way I can collaborate to this issue ?

**Comment by CirXe0N** [comment]
@AmanJain27 Yes, you can help with the code review once the PR is open.

**Comment by VincentHch** [comment]
@shahraizali Are you sure that a `page` argument is more relevant than a `limit` and `offset` one ? Because there can be multiple way of representing a page (ex: 10/50/100 lines per page).

**Comment by VincentHch** [comment]
Btw @CirXe0N If you want I already have the function written for this issue

**Comment by CirXe0N** [comment]
@VincentHch  Thanks, but no need. I am almost done. Currently writing the tests.

**Comment by AmanJain27** [comment]
@VincentHch I think page is a better way to represent counts because a page can be represented by a particular number of results instead of number of lines as you mentioned. Besides, you get pagination in effect. You can fetch any records by just mentioning the page number.

**Comment by VincentHch** [comment]
> @VincentHch I think page is a better way to represent counts because a page can be represented by a particular number of results instead of number of lines as you mentioned. Besides, you get pagination in effect. You can fetch any records by just mentioning the page number.

The best would be to let the user decide, and adding a `page`, `limit` and `offset` param in `fetch_multiple_page`

**Comment by CirXe0N** [comment]
@shahraizali @AmanJain27 @VincentHch  @sbalasa PR is ready for review.

**Comment by tawanike** [comment]
Paid
