### ISSUE TITLE
Incorrect Bank.connection_requests() and Validator.connection_requests()

### ISSUE THREAD

**Issue by DucPhamTV** [thenewboston-developers/thenewboston-python-client#62]
If I have a bank, I would like to send connection request to a CV. The library should allow me to pass requesting node information.

Current implement:
Bank.connection_requests() sends POST request to Bank IP address, the body message is its information. So it sends connection_requests() to itself.
More detail: https://thenewboston.com/bank-api/connection-requests

**Comment by sbalasa** [comment]
Yes @DucPhamTV you are right good catch.

**Comment by DucPhamTV** [comment]
My account: ec5aa47719460ee5bcd16ab3cfe94c521d702eb9fc7d80f603762c23014f8ab8

**Comment by tawanike** [comment]
Paid
