### ISSUE TITLE
Fix annotation bug and also add missing annotations 

### ISSUE THREAD

**Issue by sbalasa** [thenewboston-developers/thenewboston-python-client#65]
1. `tnb/banks.py` and `tnb/validators.py` should return annotations as `Union[dict, list]`

2. Some attributes are missing annotations: 
         `protocol`, `port` and return `-> None` in `base_client.BaseClient.__init__`
          signature in `banks.create_validator_confirmation_service`
          message in `banks.send_confirmation_block`

**Comment by makaramkd** [comment]
Ill take this. :)

**Comment by sbalasa** [comment]
Sure :)
